[workspace]
members = ["macros"]

[workspace.package]
version = "0.1.0"
edition = "2024"

[package]
name = "vibecode"
version.workspace = true
edition.workspace = true

[dependencies]
vibecode-macros = { path = "macros", version = "0.1.0" }

[dev-dependencies]
trybuild = "1.0.114"
